"""Does the model score non-speech as synthetic, and what does that make its class?

    .venv\\Scripts\\python.exe -m ml.tools.ood

The question: is the model's positive class "synthetic", or is it "not-ASVspoof"?
If Gaussian noise and a synthesised chord bed score high, the decision boundary is
not where it needs to be, and channel augmentation cannot move it there because the
problem is not the channel.

Six conditions, five repetitions each, one run, one checkpoint, all through the
config in `FROZEN.md`. The two genuine controls are in the **same run** as the four
probes deliberately: a comparison across two runs measures the runs as well as the
conditions.

Every item is exactly one 4.0375 s window, so no row differs from another in how many
windows went into it. That matters more than it sounds: on short clips the score
moves nearly the full range with window position (`ml/README.md`).

Each item is scored twice and both are recorded:

  ood         through the activity gate, the ordinary path
  ood_novad   the same window straight to the model, gate bypassed

A gate failure is a result, not a hole, so it is written as `vad_status FAIL` with an
empty score. The bypassed row is what the model says regardless, which is the number
Rule 1 of the H+4 gate reads.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

from ml.checks.machine_fingerprint import MachineFingerprintCheck
from ml.eval import probes, runlog
from ml.eval.activity import VAD_FAIL, VAD_PASS, select_windows, speech_seconds
from ml.eval.canonical import SAMPLE_RATE, load
from ml.paths import model_root
from ml.tools.frozen_config import CHECKPOINT, collect
from ml.tools.sweep import WINDOW_SAMPLES, build_check, score_window

#: Repetitions per condition. Five is what the brief specifies; it is enough to show
#: a range and nowhere near enough to be a rate, and every figure says so.
REPETITIONS = 5

#: The longest bonafide clip in the ASVspoof 2019 LA eval split, 13.011 s, found by
#: scanning all 7,355. The median is 3.196 s and only 15 clips hold two windows, so
#: this is the only way to draw five distinct segments from one studio clip.
STUDIO_CLIP = "LA_E_4770353"

#: The genuine phone control. spk_02 sits in the middle of our five recordings
#: (0.678 of a 0.436 to 0.990 range), so the control is not the easiest or the
#: hardest case we have.
PHONE_SOURCE = "Downloads/Goutham.mp4"
PHONE_SPEAKER = "speaker_b"

#: Conditions whose mean becomes S_ood. The genuine controls are excluded: they are
#: the comparison, not part of the statistic.
PROBE_CONDITIONS = ("white_noise", "pink_noise", "music", "silence_dither")


def probe_rows(
    check: MachineFingerprintCheck, commit: str, repetitions: int
) -> list[runlog.Row]:
    rows: list[runlog.Row] = []
    for condition in PROBE_CONDITIONS:
        generate = probes.GENERATORS[condition]
        for seed in range(repetitions):
            window = generate(WINDOW_SAMPLES, np.random.default_rng(seed))
            rows += score_both(
                window,
                filename=f"{condition}_{seed}",
                label="non_speech",
                dataset="synthetic_probe",
                channel="n/a",
                speaker="n/a",
                notes=f"{condition}, seed={seed}, generated by ml/eval/probes.py",
                check=check,
                commit=commit,
            )
    return rows


def control_rows(
    check: MachineFingerprintCheck,
    source_root: Path,
    cache: Path,
    commit: str,
    repetitions: int,
) -> list[runlog.Row]:
    from ml.train.dataset import load_flac

    corpus = model_root().parent / "data" / "LA"
    studio_path = corpus / "ASVspoof2019_LA_eval" / "flac" / f"{STUDIO_CLIP}.flac"
    if not studio_path.exists():
        raise SystemExit(f"missing studio control clip: {studio_path}")

    rows: list[runlog.Row] = []
    for condition, audio, dataset, channel, speaker, origin in (
        (
            "genuine_studio",
            load_flac(studio_path),
            "asvspoof",
            "studio",
            "n/a",
            STUDIO_CLIP,
        ),
        (
            "genuine_phone",
            load(source_root / PHONE_SOURCE, cache),
            "internal",
            "phone",
            PHONE_SPEAKER,
            Path(PHONE_SOURCE).name,
        ),
    ):
        overlap = probes.overlap_fraction(audio.size, repetitions, WINDOW_SAMPLES)
        note = (
            f"{condition}, {repetitions} segments of {origin}, "
            f"{audio.size / SAMPLE_RATE:.2f} s, segment overlap {overlap:.2f}"
        )
        for index, window in enumerate(
            probes.segments(audio, repetitions, WINDOW_SAMPLES)
        ):
            rows += score_both(
                window,
                filename=f"{condition}_{index}",
                label="genuine",
                dataset=dataset,
                channel=channel,
                speaker=speaker,
                notes=note,
                check=check,
                commit=commit,
            )
    return rows


def score_both(
    window: np.ndarray,
    *,
    filename: str,
    label: str,
    dataset: str,
    channel: str,
    speaker: str,
    notes: str,
    check: MachineFingerprintCheck,
    commit: str,
) -> list[runlog.Row]:
    """One window, scored through the gate and again with the gate bypassed."""
    selection = select_windows(window, WINDOW_SAMPLES)
    gated = (
        np.mean([s for s in (score_window(check, c) for c in selection.windows) if s is not None])
        if selection.windows
        else None
    )
    if gated is not None and not np.isfinite(gated):
        gated = None
    raw = score_window(check, window)
    if raw is None:
        raise RuntimeError(f"{filename}: the scorer emitted no signal on a raw window")

    common = {
        "speaker": speaker,
        "label": label,
        "dataset": dataset,
        "channel": channel,
        "duration_s": window.size / SAMPLE_RATE,
        "sample_rate": SAMPLE_RATE,
        "speech_s": speech_seconds(window),
        "checkpoint": CHECKPOINT,
        "frozen_commit": commit,
    }
    print(
        f"  {filename:<20} gated "
        f"{'FAIL' if gated is None else f'{float(gated):.4f}':>6}  "
        f"raw {raw:.4f}  {selection.status}",
        file=sys.stderr,
    )
    return [
        runlog.Row(
            run_id="ood",
            filename=filename,
            vad_status=VAD_PASS if gated is not None else VAD_FAIL,
            score=None if gated is None else float(gated),
            notes=notes if gated is not None else f"{notes}; {selection.reason}",
            **common,  # type: ignore[arg-type]
        ),
        runlog.Row(
            run_id="ood_novad",
            filename=filename,
            vad_status=VAD_PASS,
            score=raw,
            notes=f"{notes}; activity gate bypassed",
            **common,  # type: ignore[arg-type]
        ),
    ]


def condition_of(filename: str) -> str:
    """`white_noise_3` -> `white_noise`. The trailing index is the repetition."""
    return filename.rsplit("_", 1)[0]


def summarise(rows: list[runlog.Row]) -> float:
    """Print per-condition means and return S_ood."""
    by_condition: dict[tuple[str, str], list[runlog.Row]] = {}
    for row in rows:
        by_condition.setdefault((row.run_id, condition_of(row.filename)), []).append(row)

    for run_id, title in (
        ("ood", "through the activity gate"),
        ("ood_novad", "gate bypassed, the raw model response"),
    ):
        header = (
            f"\n{title}\n{'condition':<16} {'n':>3} {'fail':>5} "
            f"{'mean':>7} {'min':>7} {'max':>7} {'range':>7}"
        )
        print(header)
        print("-" * (len(header.splitlines()[-1])))
        for condition in (*PROBE_CONDITIONS, "genuine_studio", "genuine_phone"):
            group = by_condition.get((run_id, condition), [])
            scored = [r.score for r in group if r.score is not None]
            failed = len(group) - len(scored)
            if not scored:
                print(f"{condition:<16} {len(group):>3} {failed:>5} {'-':>7}")
                continue
            a = np.asarray(scored)
            print(
                f"{condition:<16} {len(group):>3} {failed:>5} {a.mean():>7.3f} "
                f"{a.min():>7.3f} {a.max():>7.3f} {a.max() - a.min():>7.3f}"
            )

    probe_scores = [
        r.score
        for r in rows
        if r.run_id == "ood_novad"
        and condition_of(r.filename) in PROBE_CONDITIONS
        and r.score is not None
    ]
    s_ood = float(np.mean(probe_scores))
    array = np.asarray(probe_scores)
    print(
        f"\nS_ood = {s_ood:.4f}   "
        f"mean over {len(probe_scores)} non-speech probes, gate bypassed, "
        f"range {array.min():.3f} to {array.max():.3f}"
    )
    print(
        "Rule 1 of the H+4 gate fires at S_ood > 0.85: "
        f"{'FIRES' if s_ood > 0.85 else 'does not fire'}"
    )
    return s_ood


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source-root", type=Path, default=Path.home())
    parser.add_argument("--out", type=Path, default=Path("data/results/ood.csv"))
    parser.add_argument("--cache-dir", type=Path, default=None)
    parser.add_argument("--device", default=None)
    parser.add_argument("--repetitions", type=int, default=REPETITIONS)
    args = parser.parse_args(argv)

    cache = args.cache_dir or args.out.parent / "canonical"
    fields = collect()
    commit = fields["frozen_commit"]
    print(f"model    {fields['model_id']}  {Path(fields['checkpoint_path']).name}")
    print(f"commit   {commit}")
    print(f"window   {fields['window_s']} s, one window per item\n")

    check = build_check("xlsr-aasist", args.device)

    print("probes", file=sys.stderr)
    rows = probe_rows(check, commit, args.repetitions)
    print("controls", file=sys.stderr)
    rows += control_rows(check, args.source_root, cache, commit, args.repetitions)

    runlog.write(rows, args.out)
    print(f"\nwrote {len(rows)} rows to {args.out}")
    summarise(rows)
    print(
        "\nEvidence, not a verdict. n=5 per condition, one checkpoint, one run. "
        "A probe score is what the model says about non-speech, not a rate."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
